### ISSUE TITLE
Atmosphere-Operator CrashLoopBackOff issue

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/atmosphere#129]
The atmosphere operator is doing the work needed to ensure resources but ends up in a CrashLoopBackOff status regularly. In 3 days I have seen 636 restarts and the entire log looks as follows:

```log
❯ kubectl -n openstack logs atmosphere-operator-5b7f44dc7d-kxk68
2022-10-13 14:13.15 [info     ] Starting Atmosphere operator
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=Namespace name=monitoring
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=Namespace name=kube-system
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=Namespace name=cert-manager
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=Namespace name=openstack
2022-10-13 14:13.15 [info     ] Ensured resource               kind=Namespace name=kube-system
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=ceph namespace=kube-system requires=['namespace-kube-system']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=Namespace name=openstack
2022-10-13 14:13.15 [info     ] Ensured resource               kind=Namespace name=cert-manager
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=percona namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=Namespace name=monitoring
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=openstack-helm-infra namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=bitnami namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=ceph namespace=kube-system requires=['namespace-kube-system']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=Secret name=atmosphere-memcached namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=percona namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=coredns namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=bitnami namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=openstack-helm namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=openstack-helm-infra namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=Service name=memcached-metrics namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=Secret name=atmosphere-memcached namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=prometheus-community namespace=monitoring requires=['namespace-monitoring']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=Service name=memcached-metrics namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=jetstack namespace=cert-manager requires=['namespace-cert-manager']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=openstack-helm namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRepository name=node-feature-discovery namespace=monitoring requires=['namespace-monitoring']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=coredns namespace=openstack requires=['namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRelease name=pxc-operator namespace=openstack requires=['helm-repository-openstack-percona', 'namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=prometheus-community namespace=monitoring requires=['namespace-monitoring']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRelease name=memcached namespace=openstack requires=['secret-openstack-atmosphere-memcached', 'helm-repository-openstack-openstack-helm-infra', 'namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=jetstack namespace=cert-manager requires=['namespace-cert-manager']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRelease name=cert-manager namespace=cert-manager requires=['helm-repository-cert-manager-jetstack', 'namespace-cert-manager']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRepository name=node-feature-discovery namespace=monitoring requires=['namespace-monitoring']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=HelmRelease name=node-feature-discovery namespace=monitoring requires=['helm-repository-monitoring-node-feature-discovery', 'namespace-monitoring']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRelease name=pxc-operator namespace=openstack requires=['helm-repository-openstack-percona', 'namespace-openstack']
2022-10-13 14:13.15 [debug    ] Ensuring resource              kind=PerconaXtraDBCluster name=percona-xtradb namespace=openstack requires=['helm-release-openstack-pxc-operator', 'namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRelease name=memcached namespace=openstack requires=['secret-openstack-atmosphere-memcached', 'helm-repository-openstack-openstack-helm-infra', 'namespace-openstack']
2022-10-13 14:13.15 [info     ] Ensured resource               kind=HelmRelease name=cert-manager namespace=cert-manager requires=['helm-repository-cert-manager-jetstack', 'namespace-cert-manager']
2022-10-13 14:13.16 [info     ] Ensured resource               kind=PerconaXtraDBCluster name=percona-xtradb namespace=openstack requires=['helm-release-openstack-pxc-operator', 'namespace-openstack']
2022-10-13 14:13.16 [debug    ] Ensuring resource              kind=Issuer name=openstack namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'namespace-openstack']
2022-10-13 14:13.16 [debug    ] Ensuring resource              kind=Issuer name=self-signed namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'namespace-openstack']
2022-10-13 14:13.16 [debug    ] Ensuring resource              kind=HelmRelease name=rabbitmq-cluster-operator namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'helm-repository-openstack-bitnami', 'namespace-openstack']
2022-10-13 14:13.17 [info     ] Ensured resource               kind=Issuer name=openstack namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'namespace-openstack']
2022-10-13 14:13.17 [debug    ] Ensuring resource              kind=Certificate name=self-signed-ca namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'namespace-openstack']
2022-10-13 14:13.17 [info     ] Ensured resource               kind=Issuer name=self-signed namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'namespace-openstack']
2022-10-13 14:13.18 [info     ] Ensured resource               kind=Certificate name=self-signed-ca namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'namespace-openstack']
2022-10-13 14:13.18 [info     ] Ensured resource               kind=HelmRelease name=rabbitmq-cluster-operator namespace=openstack requires=['helm-release-cert-manager-cert-manager', 'helm-repository-openstack-bitnami', 'namespace-openstack']
2022-10-13 14:13.19 [debug    ] Ensuring resource              kind=RabbitmqCluster name=keystone namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.19 [debug    ] Ensuring resource              kind=RabbitmqCluster name=senlin namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.19 [debug    ] Ensuring resource              kind=RabbitmqCluster name=cinder namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.20 [info     ] Ensured resource               kind=RabbitmqCluster name=keystone namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.20 [debug    ] Ensuring resource              kind=RabbitmqCluster name=nova namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.20 [info     ] Ensured resource               kind=RabbitmqCluster name=senlin namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.20 [debug    ] Ensuring resource              kind=RabbitmqCluster name=glance namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.20 [info     ] Ensured resource               kind=RabbitmqCluster name=cinder namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.20 [debug    ] Ensuring resource              kind=RabbitmqCluster name=heat namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.22 [info     ] Ensured resource               kind=RabbitmqCluster name=glance namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.22 [debug    ] Ensuring resource              kind=RabbitmqCluster name=neutron namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.22 [info     ] Ensured resource               kind=RabbitmqCluster name=nova namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.22 [debug    ] Ensuring resource              kind=RabbitmqCluster name=barbican namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.22 [info     ] Ensured resource               kind=RabbitmqCluster name=heat namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.24 [info     ] Ensured resource               kind=RabbitmqCluster name=barbican namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
2022-10-13 14:13.24 [info     ] Ensured resource               kind=RabbitmqCluster name=neutron namespace=openstack requires=['helm-release-openstack-rabbitmq-cluster-operator', 'namespace-openstack']
Traceback (most recent call last):
  File "/app/.venv/bin/atmosphere-operator", line 6, in <module>
    sys.exit(main())
  File "/app/atmosphere/cmd/operator.py", line 15, in main
    engine.run()
  File "/app/.venv/lib/python3.10/site-packages/taskflow/engines/action_engine/engine.py", line 247, in run
    for _state in self.run_iter(timeout=timeout):
  File "/app/.venv/lib/python3.10/site-packages/taskflow/engines/action_engine/engine.py", line 340, in run_iter
    failure.Failure.reraise_if_any(er_failures)
  File "/app/.venv/lib/python3.10/site-packages/taskflow/types/failure.py", line 338, in reraise_if_any
    failures[0].reraise()
  File "/app/.venv/lib/python3.10/site-packages/taskflow/types/failure.py", line 350, in reraise
    raise value
  File "/app/.venv/lib/python3.10/site-packages/taskflow/engines/action_engine/executor.py", line 52, in _execute_task
    result = task.execute(**arguments)
  File "/app/atmosphere/tasks/kubernetes/base.py", line 79, in execute
    self.wait_for_resource(resource)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/app/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f71333198d0 state=finished returned bool>]
```

Now this could be due to something different in my environment, but I am not getting a lot of context from the logs so I am unsure if its due to something different on my end or something wrong with the container in general.

**Comment by mnaser** [comment]
@runlevel-six the logs are not great, but I think the issue here is that the helm release never transitioned to applied.

can you check all the helm releases and see if one is failed?

```
kubectl get helmrelease --all-namespaces
```

**Comment by runlevel-six** [comment]
@mnaser you are right. I didn't realize that node-feature-discovery had been pulled into the operator - we deploy that separately so I suspect that is why the HelmRelease is failing. 

Just curious, in the same manner that you did ingress-nginx, would it be feasible to make any of the non-OpenStack components installed by the operator flagged to be skipped (or with overrides if we use it but have a different configuration)?

**Comment by mnaser** [comment]
@runlevel-six we should be able to do that moving forward, but I think we hadn't gotten around going back to the existing tools.

I'll try to find sometime to flip all of the components to be configurable

**Comment by runlevel-six** [comment]
Closing since the answer was determined, and https://github.com/vexxhost/atmosphere/issues/159 opened with a request for the new feature that would resolve this.
