### ISSUE TITLE
Missing packages in glance image

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#36]
Currently, when we use cinder as a backend for glance images, the following traceback is raised:

```
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi [req-b4c41781-0afb-4173-9a8d-e052c658b0df dd5664a9739d4afba929b37d3f123f28 f5ed2d21437644adb2669f9ade9c949b - default default] Caught error: 'NoneType' object has no attribute 'Client': AttributeError: 'NoneType' object has no attribute 'Client'
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi Traceback (most recent call last):
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/common/wsgi.py", line 1353, in __call__
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     action_result = self.dispatch(self.controller, action,
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/common/wsgi.py", line 1397, in dispatch
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     return method(*args, **kwargs)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/common/utils.py", line 416, in wrapped
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     return func(self, req, *args, **kwargs)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/api/v2/image_data.py", line 300, in upload
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     self._restore(image_repo, image)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     self.force_reraise()
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     raise self.value
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/api/v2/image_data.py", line 165, in upload
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     image.set_data(data, size, backend=backend)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/domain/proxy.py", line 208, in set_data
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     self.base.set_data(data, size, backend=backend, set_active=set_active)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/notifier.py", line 501, in set_data
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     _send_notification(notify_error, 'image.upload', msg)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     self.force_reraise()
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     raise self.value
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/notifier.py", line 447, in set_data
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     self.repo.set_data(data, size, backend=backend,
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/api/policy.py", line 273, in set_data
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     return self.image.set_data(*args, **kwargs)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/quota/__init__.py", line 322, in set_data
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     self.image.set_data(data, size=size, backend=backend,
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/location.py", line 567, in set_data
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     self._upload_to_store(data, verifier, backend, size)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/location.py", line 473, in _upload_to_store
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     loc_meta) = self.store_api.add_to_backend_with_multihash(
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/backend.py", line 490, in add_to_backend_with_multihash
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     return store_add_to_backend_with_multihash(
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/backend.py", line 467, in store_add_to_backend_with_multihash
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     (location, size, checksum, multihash, metadata) = store.add(
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/driver.py", line 279, in add_adapter
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     metadata_dict) = store_add_fun(*args, **kwargs)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/capabilities.py", line 176, in op_checker
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     return store_op_fun(store, *args, **kwargs)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/_drivers/cinder.py", line 819, in add
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     client = self.get_cinderclient(context)
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/_drivers/cinder.py", line 508, in get_cinderclient
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi     c = cinderclient.Client(
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi AttributeError: 'NoneType' object has no attribute 'Client'
2022-09-02 17:59:11.475 8 ERROR glance.common.wsgi 
```

This is possible due to missing packages inside glance images like `os_brick` and `python-cinderclient`

**Comment by mnaser** [comment]
@guilhermesteinmuller 

https://github.com/vexxhost/atmosphere/blob/main/ci/openstack-image-build-env

Could you add both those packages to PIP_PACKAGES?

**Comment by guilhermesteinmuller** [comment]
> @guilhermesteinmuller
> 
> https://github.com/vexxhost/atmosphere/blob/main/ci/openstack-image-build-env
> 
> Could you add both those packages to PIP_PACKAGES?

sure will provide PR shortly

**Comment by mnaser** [comment]
@guilhermesteinmuller I'm working on this since the image build process is currently a bit broken, working on it here and will push up a PR soon.

**Comment by mnaser** [comment]
This is pending on https://github.com/vexxhost/atmosphere/pull/38
