### ISSUE TITLE
Barbican fails to deploy with missing API paste

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#431]
The removal of API paste files have caused Barbican to fully stop working.

```
Respawned uWSGI worker 1 (new pid: 138)
Loading paste environment: config:/etc/barbican/barbican-api-paste.ini
Traceback (most recent call last):
  File "/var/lib/openstack/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/var/lib/openstack/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 275, in loadobj
    context = loadcontext(
  File "/var/lib/openstack/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 299, in loadcontext
    return _loaders[scheme](
  File "/var/lib/openstack/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 323, in _loadconfig
    loader = ConfigLoader(path)
  File "/var/lib/openstack/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 399, in __init__
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/barbican/barbican-api-paste.ini'
```

This is is a regression from the past change we've done, we need to do two things.  We should:

1) Fix this issue and release ASAP
1) Add a Barbican test to Tempest to make sure we dont break it

**Comment by okozachenko1203** [comment]
1. this should be fixed by #432 
2. https://review.opendev.org/c/openstack/openstack-helm-images/+/840528 there is already barbican-tempest-plugin installed in the upstream tempest image. Do we us this?
