### ISSUE TITLE
Glance with Cinder backend

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#46]
There seems to be a list of outstanding issues when trying to use Glance with Cinder as a backend, this issue tracks all the outstanding issues:

- [x] https://github.com/vexxhost/atmosphere/issues/36
- [x] #47
- [ ] #48

**Comment by mnaser** [comment]
The traceback for the other failure:

```
2022-09-08 19:56:07.175 9 ERROR glance_store._drivers.cinder [req-fa2a92b6-e558-4ac2-aef7-627b912fcac8 dd5664a9739d4afba929b37d3f123f28 f5ed2d21437644adb2669f9ade9c949b - default default] Failed to write to volume 3f4b821a-878a-4f23-a951-dfdffc2fe757.: oslo_privsep.daemon.FailedToDropPrivileges: privsep helper command exited non-zero (1)
2022-09-08 19:56:07.274 9 ERROR glance.api.v2.image_data [req-fa2a92b6-e558-4ac2-aef7-627b912fcac8 dd5664a9739d4afba929b37d3f123f28 f5ed2d21437644adb2669f9ade9c949b - default default] Failed to upload image data due to internal error: oslo_privsep.daemon.FailedToDropPrivileges: privsep helper command exited non-zero (1)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi [req-fa2a92b6-e558-4ac2-aef7-627b912fcac8 dd5664a9739d4afba929b37d3f123f28 f5ed2d21437644adb2669f9ade9c949b - default default] Caught error: privsep helper command exited non-zero (1): oslo_privsep.daemon.FailedToDropPrivileges: privsep helper command exited non-zero (1)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi Traceback (most recent call last):
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/common/wsgi.py", line 1353, in __call__
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     action_result = self.dispatch(self.controller, action,
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/common/wsgi.py", line 1397, in dispatch
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return method(*args, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/common/utils.py", line 416, in wrapped
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return func(self, req, *args, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/api/v2/image_data.py", line 300, in upload
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self._restore(image_repo, image)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self.force_reraise()
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     raise self.value
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/api/v2/image_data.py", line 165, in upload
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     image.set_data(data, size, backend=backend)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/domain/proxy.py", line 208, in set_data
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self.base.set_data(data, size, backend=backend, set_active=set_active)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/notifier.py", line 501, in set_data
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     _send_notification(notify_error, 'image.upload', msg)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self.force_reraise()
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     raise self.value
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/notifier.py", line 447, in set_data
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self.repo.set_data(data, size, backend=backend,
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/api/policy.py", line 273, in set_data
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return self.image.set_data(*args, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/quota/__init__.py", line 322, in set_data
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self.image.set_data(data, size=size, backend=backend,
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/location.py", line 567, in set_data
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self._upload_to_store(data, verifier, backend, size)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance/location.py", line 473, in _upload_to_store
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     loc_meta) = self.store_api.add_to_backend_with_multihash(
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/backend.py", line 490, in add_to_backend_with_multihash
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return store_add_to_backend_with_multihash(
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/backend.py", line 467, in store_add_to_backend_with_multihash
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     (location, size, checksum, multihash, metadata) = store.add(
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/driver.py", line 279, in add_adapter
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     metadata_dict) = store_add_fun(*args, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/capabilities.py", line 176, in op_checker
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return store_op_fun(store, *args, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/_drivers/cinder.py", line 898, in add
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     with self._open_cinder_volume(client, volume, 'wb') as f:
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return next(self.gen)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/glance_store/_drivers/cinder.py", line 654, in _open_cinder_volume
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     properties = connector.get_connector_properties(
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/os_brick/utils.py", line 141, in trace_logging_wrapper
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return f(*args, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/os_brick/initiator/connector.py", line 232, in get_connector_properties
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     connector.get_connector_properties(
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/os_brick/initiator/connectors/iscsi.py", line 68, in get_connector_properties
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     initiator = iscsi.get_initiator()
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/os_brick/initiator/connectors/iscsi.py", line 982, in get_initiator
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     lines, _err = self._execute('cat', file_path, run_as_root=True,
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/os_brick/executor.py", line 52, in _execute
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     result = self.__execute(*args, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/os_brick/privileged/rootwrap.py", line 172, in execute
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     return execute_root(*cmd, **kwargs)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_privsep/priv_context.py", line 246, in _wrap
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     self.start()
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_privsep/priv_context.py", line 258, in start
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     channel = daemon.RootwrapClientChannel(context=self)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi   File "/var/lib/openstack/lib/python3.8/site-packages/oslo_privsep/daemon.py", line 367, in __init__
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi     raise FailedToDropPrivileges(msg)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi oslo_privsep.daemon.FailedToDropPrivileges: privsep helper command exited non-zero (1)
2022-09-08 19:56:07.310 9 ERROR glance.common.wsgi 
2022-09-08 19:56:07.326 9 INFO eventlet.wsgi.server [req-fa2a92b6-e558-4ac2-aef7-627b912fcac8 dd5664a9739d4afba929b37d3f123f28 f5ed2d21437644adb2669f9ade9c949b - default default] 10.0.140.10,10.0.2.26 - - [08/Sep/2022 19:56:07] "PUT /v2/images/81b46063-993b-4861-b170-bfee0101506a/file HTTP/1.1" 500 317 2.979938
```

I think the issue here is that rootwrap is not configured for Glance.

**Comment by mnaser** [comment]
I think we'll have to do something like this but for Glance:

https://github.com/openstack/openstack-helm/blob/3bc81054b0918678c5932663ea72821621280d5c/cinder/values.yaml#L628-L632
https://github.com/openstack/openstack-helm/blob/3bc81054b0918678c5932663ea72821621280d5c/cinder/templates/configmap-etc.yaml#L154
https://github.com/openstack/openstack-helm/blob/3bc81054b0918678c5932663ea72821621280d5c/cinder/templates/deployment-volume.yaml#L219-L229

**Comment by mnaser** [comment]
@guilhermesteinmuller leave this to me, I will work on a fix for this, it involves changing the Helm charts.
