### ISSUE TITLE
Horizon image on Quay errors: wallaby, xena, and yoga tags affected

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/atmosphere#68]
When testing out the horizon image on `quay.io/vexxhost/horizon:yoga` I am seeing the following error occur which indicates that the version of mysql installed in that container image is not compatible. I see this error with the `yoga` tag.

Error reported in `yoga` tag:

```log
Traceback (most recent call last):
  File "/tmp/manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/openstack/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/lib/openstack/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/var/lib/openstack/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/openstack/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/var/lib/openstack/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/openstack/lib/python3.8/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/var/lib/openstack/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/var/lib/openstack/lib/python3.8/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/var/lib/openstack/lib/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/var/lib/openstack/lib/python3.8/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/var/lib/openstack/lib/python3.8/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/var/lib/openstack/lib/python3.8/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/var/lib/openstack/lib/python3.8/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/var/lib/openstack/lib/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/var/lib/openstack/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 36, in <module>
    raise ImproperlyConfigured('mysqlclient 1.4.0 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.4.0 or newer is required; you have 1.0.2.
```

In the `xena` and `wallaby` tags I get a different error:

```log
Execution of msgfmt failed: /var/lib/openstack/lib/python3.8/site-packages/monitoring/locale/ko_KR/LC_MESSAGES/django.po:35: end-of-line within string
msgfmt: found 1 fatal error
Execution of msgfmt failed: /var/lib/openstack/lib/python3.8/site-packages/monitoring/locale/en_GB/LC_MESSAGES/django.po:36: end-of-line within string
/var/lib/openstack/lib/python3.8/site-packages/monitoring/locale/en_GB/LC_MESSAGES/django.po:49: end-of-line within string
msgfmt: found 2 fatal errors
Execution of msgfmt failed: /var/lib/openstack/lib/python3.8/site-packages/monitoring/locale/ja/LC_MESSAGES/django.po:39: end-of-line within string
msgfmt: found 1 fatal error
Execution of msgfmt failed: /var/lib/openstack/lib/python3.8/site-packages/monitoring/locale/id/LC_MESSAGES/django.po:31: end-of-line within string
msgfmt: found 1 fatal error
CommandError: compilemessages generated one or more errors.
```

The OpenStack Helm image `openstackhelm/horizon:xena-ubuntu_focal` does not have either of these errors nor does `us-docker.pkg.dev/vexxhost-infra/openstack/horizon:wallaby`

**Comment by mnaser** [comment]
@runlevel-six I think that's two distinct issues here, let me check out the Xena and wallaby ones first since those are probably an easier fix.

**Comment by mnaser** [comment]
It looks like that error is the integration of the `monasca-ui` component.  Pulling this commit in likely has broken it:

https://github.com/openstack/monasca-ui/commit/097d12aee254ab8bd89b87f3e7463a996e6813d9

**Comment by mnaser** [comment]
alright, I think it's because we install those extra packages from `master` instead of having them constrained to the release of the image (i.e. `monasca-ui` from master with `horizon` from `stable/wallaby`).

I'll see what we can do about this.

**Comment by mnaser** [comment]
trying this here:

https://github.com/vexxhost/atmosphere/commit/7f45988ebf9db38463b9e91808b498cc9072e86f
