### ISSUE TITLE
Set DNS name at a floating IP

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#730]
When I try to gave a floating IP address a DNS name when Designate is installed I get the following error:

```LOG
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource Traceback (most recent call last):
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/api/v2/resource.py", line 98, in resource
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     result = method(request=request, **args)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/api/v2/base.py", line 438, in create
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return self._create(request, body, **kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 140, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     with excutils.save_and_reraise_exception():
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.force_reraise()
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise self.value
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 138, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_db/api.py", line 144, in wrapper
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     with excutils.save_and_reraise_exception() as ectxt:
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.force_reraise()
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise self.value
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_db/api.py", line 142, in wrapper
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 186, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     with excutils.save_and_reraise_exception():
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.force_reraise()
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise self.value
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 184, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return f(*dup_args, **dup_kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/api/v2/base.py", line 562, in _create
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     obj = do_create(body)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/api/v2/base.py", line 541, in do_create
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     with excutils.save_and_reraise_exception():
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.force_reraise()
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise self.value
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/api/v2/base.py", line 537, in do_create
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return obj_creator(request.context, **kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/services/ovn_l3/plugin.py", line 276, in create_floatingip
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     fip = super(OVNL3RouterPlugin, self).create_floatingip(
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/db/l3_db.py", line 2235, in create_floatingip
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     floatingip_dict = super(L3_NAT_db_mixin, self).create_floatingip(
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 226, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return f_with_retry(*args, **kwargs,
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 140, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     with excutils.save_and_reraise_exception():
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.force_reraise()
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise self.value
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 138, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_db/api.py", line 144, in wrapper
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     with excutils.save_and_reraise_exception() as ectxt:
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.force_reraise()
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise self.value
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_db/api.py", line 142, in wrapper
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 186, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     with excutils.save_and_reraise_exception():
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 227, in __exit__
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.force_reraise()
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise self.value
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron_lib/db/api.py", line 184, in wrapped
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return f(*dup_args, **dup_kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/db/l3_db.py", line 1567, in create_floatingip
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return self._create_floatingip(context, floatingip, initial_status)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/db/l3_db.py", line 1555, in _create_floatingip
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self._process_dns_floatingip_create_postcommit(context,
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/db/dns_db.py", line 114, in _process_dns_floatingip_create_postcommit
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self._add_ips_to_external_dns_service(
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/db/dns_db.py", line 246, in _add_ips_to_external_dns_service
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     self.dns_driver.create_record_set(context, dns_domain, dns_name,
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/services/externaldns/drivers/designate/driver.py", line 98, in create_record_set
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     designate, designate_admin = get_clients(context)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/neutron/services/externaldns/drivers/designate/driver.py", line 54, in get_clients
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     admin_auth = loading.load_auth_from_conf_options(
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/keystoneauth1/loading/conf.py", line 135, in load_from_conf_options
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return plugin.load_from_options_getter(_getter, **kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/keystoneauth1/loading/base.py", line 187, in load_from_options_getter
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     return self.load_from_options(**kwargs)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource   File "/var/lib/openstack/lib/python3.10/site-packages/keystoneauth1/loading/base.py", line 162, in load_from_options
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource     raise exceptions.MissingRequiredOptions(missing_required)
2023-11-27 20:26:51.085 10 ERROR neutron.api.v2.resource keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url
```

**Comment by okozachenko1203** [comment]
@mpiscaer It is because your neutron config includes no `designate` section or invalid ones.
Please share the neutron config and also you can refer to this https://docs.openstack.org/neutron/latest/configuration/neutron.html#designate

**Comment by okozachenko1203** [comment]
> I have currently the following in neutron_helm_values:
> 
> ```
> neutron_helm_values:
>   conf:
>     neutron:
>       DEFAULT:
>         api_workers: 24
>         rpc_workers: 24
>         global_physnet_mtu: 9000
>         service_plugins: ovn-router,vpnaas,port_forwarding,segments
>       placement:
>         os_region_name: "{{ openstack_helm_endpoints_region_name }}"
>         username: "placement-{{ openstack_helm_endpoints_placement_region_name }}"
>         password: "{{ openstack_helm_endpoints_placement_keystone_password }}"
>       AGENT:
>         availability_zone: nova
>     plugins:
>       ml2_conf:
>         ml2_type_vlan:
>           network_vlan_ranges: "external:7:799,external:869:4093"
>         ml2:
>           physical_network_mtus: "external:1500"
>           path_mtu: 1550
>           tenant_network_types: geneve,vlan
>     l3_agent:
>       AGENT:
>         extensions: vpnaas,port_forwarding
>       DEFAULT:
>         ha_vrrp_auth_password: "{{ secret_l3_vrrp_auth_password }}"
>     policy:
>       create_port:fixed_ips:ip_address: rule:context_is_advsvc or rule:admin_or_network_owner or rule:shared
>       update_port:fixed_ips:ip_address: rule:context_is_advsvc or rule:admin_or_network_owner or rule:shared
> ```
> 
> I probably I need to add a designate section in the conf.neutron .
> 
> adding a Designate section in __neutron_helm_values from Atmosphere is probably no possible there not every install base have Designate installed?

There is no need to configure designate section manually. This is osh upstream bug surely. Let me fix

**Comment by okozachenko1203** [comment]
https://review.opendev.org/c/openstack/openstack-helm/+/902767
