### ISSUE TITLE
Manila DB error at a fresh install

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#910]
At a fresh install I get a DB of for Manila.

I use the Zed images: `manila:zed@sha256:5c590bf7fc738e8ab11dc267285c207a06098bc113bd70696f6928a7a887e844`, the Bobcat `manila:2023.2@sha256:684e4fbdbfbd032d298ce513399f0bd3ef64e7aa12016d7099d1cb0db2f9b4f7`
image works without any problem.

```
(feature/mpc/Senlin&Manila)root@ctl1:~# kubectl -n openstack logs pod/manila-db-sync-vcjtg
+ exec manila-manage db sync
2024-01-20 19:17:48.873 1 INFO alembic.runtime.migration [-] Context impl MySQLImpl.
2024-01-20 19:17:48.876 1 INFO alembic.runtime.migration [-] Will assume non-transactional DDL.
2024-01-20 19:17:48.933 1 INFO alembic.runtime.migration [-] Running upgrade 3db9992c30f3 -> 5077ffcc5f1c, add_share_instances
2024-01-20 19:17:48.998 1 CRITICAL manila [-] Unhandled error: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1050, "Table 'share_instances' already exists")
[SQL:
CREATE TABLE share_instances (
        created_at DATETIME,
        updated_at DATETIME,
        deleted_at DATETIME,
        deleted VARCHAR(36),
        id VARCHAR(36) NOT NULL,
        share_id VARCHAR(36),
        host VARCHAR(255),
        status VARCHAR(255),
        scheduled_at DATETIME,
        launched_at DATETIME,
        terminated_at DATETIME,
        share_network_id VARCHAR(36),
        share_server_id VARCHAR(36),
        availability_zone VARCHAR(255),
        PRIMARY KEY (id),
        CONSTRAINT si_share_fk FOREIGN KEY(share_id) REFERENCES shares (id),
        CONSTRAINT si_share_network_fk FOREIGN KEY(share_network_id) REFERENCES share_networks (id),
        CONSTRAINT si_share_server_fk FOREIGN KEY(share_server_id) REFERENCES share_servers (id)
)CHARSET=utf8 ENGINE=InnoDB

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-20 19:17:48.998 1 ERROR manila Traceback (most recent call last):
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
2024-01-20 19:17:48.998 1 ERROR manila     self.dialect.do_execute(
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2024-01-20 19:17:48.998 1 ERROR manila     cursor.execute(statement, parameters)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
2024-01-20 19:17:48.998 1 ERROR manila     result = self._query(query)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
2024-01-20 19:17:48.998 1 ERROR manila     conn.query(q)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
2024-01-20 19:17:48.998 1 ERROR manila     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
2024-01-20 19:17:48.998 1 ERROR manila     result.read()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
2024-01-20 19:17:48.998 1 ERROR manila     first_packet = self.connection._read_packet()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
2024-01-20 19:17:48.998 1 ERROR manila     packet.raise_for_error()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-20 19:17:48.998 1 ERROR manila     err.raise_mysql_exception(self._data)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-20 19:17:48.998 1 ERROR manila     raise errorclass(errno, errval)
2024-01-20 19:17:48.998 1 ERROR manila pymysql.err.OperationalError: (1050, "Table 'share_instances' already exists")
2024-01-20 19:17:48.998 1 ERROR manila
2024-01-20 19:17:48.998 1 ERROR manila The above exception was the direct cause of the following exception:
2024-01-20 19:17:48.998 1 ERROR manila
2024-01-20 19:17:48.998 1 ERROR manila Traceback (most recent call last):
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/bin/manila-manage", line 8, in <module>
2024-01-20 19:17:48.998 1 ERROR manila     sys.exit(main())
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/cmd/manage.py", line 545, in main
2024-01-20 19:17:48.998 1 ERROR manila     fn(*fn_args)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/cmd/manage.py", line 206, in sync
2024-01-20 19:17:48.998 1 ERROR manila     return migration.upgrade(version)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/db/migration.py", line 28, in upgrade
2024-01-20 19:17:48.998 1 ERROR manila     return IMPL.upgrade(version)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/db/migrations/alembic/migration.py", line 51, in upgrade
2024-01-20 19:17:48.998 1 ERROR manila     return alembic.command.upgrade(_alembic_config(), revision or 'head')
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
2024-01-20 19:17:48.998 1 ERROR manila     script.run_env()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
2024-01-20 19:17:48.998 1 ERROR manila     util.load_python_file(self.dir, "env.py")
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
2024-01-20 19:17:48.998 1 ERROR manila     module = load_module_py(module_id, path)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
2024-01-20 19:17:48.998 1 ERROR manila     spec.loader.exec_module(module)  # type: ignore
2024-01-20 19:17:48.998 1 ERROR manila   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-01-20 19:17:48.998 1 ERROR manila   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/db/migrations/alembic/env.py", line 40, in <module>
2024-01-20 19:17:48.998 1 ERROR manila     run_migrations_online()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/db/migrations/alembic/env.py", line 35, in run_migrations_online
2024-01-20 19:17:48.998 1 ERROR manila     context.run_migrations()
2024-01-20 19:17:48.998 1 ERROR manila   File "<string>", line 8, in run_migrations
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
2024-01-20 19:17:48.998 1 ERROR manila     self.get_context().run_migrations(**kw)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
2024-01-20 19:17:48.998 1 ERROR manila     step.migration_fn(**kw)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/db/migrations/alembic/versions/5077ffcc5f1c_add_share_instances.py", line 285, in upgrade
2024-01-20 19:17:48.998 1 ERROR manila     create_share_instances_table(connection)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/manila/db/migrations/alembic/versions/5077ffcc5f1c_add_share_instances.py", line 37, in create_share_instances_table
2024-01-20 19:17:48.998 1 ERROR manila     share_instances_table = op.create_table(
2024-01-20 19:17:48.998 1 ERROR manila   File "<string>", line 8, in create_table
2024-01-20 19:17:48.998 1 ERROR manila   File "<string>", line 3, in create_table
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/operations/ops.py", line 1311, in create_table
2024-01-20 19:17:48.998 1 ERROR manila     return operations.invoke(op)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/operations/base.py", line 445, in invoke
2024-01-20 19:17:48.998 1 ERROR manila     return fn(self, operation)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 131, in create_table
2024-01-20 19:17:48.998 1 ERROR manila     operations.impl.create_table(table)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/ddl/impl.py", line 366, in create_table
2024-01-20 19:17:48.998 1 ERROR manila     self._exec(schema.CreateTable(table))
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/alembic/ddl/impl.py", line 207, in _exec
2024-01-20 19:17:48.998 1 ERROR manila     return conn.execute(construct, multiparams)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
2024-01-20 19:17:48.998 1 ERROR manila     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
2024-01-20 19:17:48.998 1 ERROR manila     return connection._execute_ddl(
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
2024-01-20 19:17:48.998 1 ERROR manila     ret = self._execute_context(
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
2024-01-20 19:17:48.998 1 ERROR manila     self._handle_dbapi_exception(
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2132, in _handle_dbapi_exception
2024-01-20 19:17:48.998 1 ERROR manila     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2024-01-20 19:17:48.998 1 ERROR manila     raise exception
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
2024-01-20 19:17:48.998 1 ERROR manila     self.dialect.do_execute(
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2024-01-20 19:17:48.998 1 ERROR manila     cursor.execute(statement, parameters)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
2024-01-20 19:17:48.998 1 ERROR manila     result = self._query(query)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
2024-01-20 19:17:48.998 1 ERROR manila     conn.query(q)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
2024-01-20 19:17:48.998 1 ERROR manila     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
2024-01-20 19:17:48.998 1 ERROR manila     result.read()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
2024-01-20 19:17:48.998 1 ERROR manila     first_packet = self.connection._read_packet()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
2024-01-20 19:17:48.998 1 ERROR manila     packet.raise_for_error()
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-20 19:17:48.998 1 ERROR manila     err.raise_mysql_exception(self._data)
2024-01-20 19:17:48.998 1 ERROR manila   File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-20 19:17:48.998 1 ERROR manila     raise errorclass(errno, errval)
2024-01-20 19:17:48.998 1 ERROR manila sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1050, "Table 'share_instances' already exists")
2024-01-20 19:17:48.998 1 ERROR manila [SQL:
2024-01-20 19:17:48.998 1 ERROR manila CREATE TABLE share_instances (
2024-01-20 19:17:48.998 1 ERROR manila  created_at DATETIME,
2024-01-20 19:17:48.998 1 ERROR manila  updated_at DATETIME,
2024-01-20 19:17:48.998 1 ERROR manila  deleted_at DATETIME,
2024-01-20 19:17:48.998 1 ERROR manila  deleted VARCHAR(36),
2024-01-20 19:17:48.998 1 ERROR manila  id VARCHAR(36) NOT NULL,
2024-01-20 19:17:48.998 1 ERROR manila  share_id VARCHAR(36),
2024-01-20 19:17:48.998 1 ERROR manila  host VARCHAR(255),
2024-01-20 19:17:48.998 1 ERROR manila  status VARCHAR(255),
2024-01-20 19:17:48.998 1 ERROR manila  scheduled_at DATETIME,
2024-01-20 19:17:48.998 1 ERROR manila  launched_at DATETIME,
2024-01-20 19:17:48.998 1 ERROR manila  terminated_at DATETIME,
2024-01-20 19:17:48.998 1 ERROR manila  share_network_id VARCHAR(36),
2024-01-20 19:17:48.998 1 ERROR manila  share_server_id VARCHAR(36),
2024-01-20 19:17:48.998 1 ERROR manila  availability_zone VARCHAR(255),
2024-01-20 19:17:48.998 1 ERROR manila  PRIMARY KEY (id),
2024-01-20 19:17:48.998 1 ERROR manila  CONSTRAINT si_share_fk FOREIGN KEY(share_id) REFERENCES shares (id),
2024-01-20 19:17:48.998 1 ERROR manila  CONSTRAINT si_share_network_fk FOREIGN KEY(share_network_id) REFERENCES share_networks (id),
2024-01-20 19:17:48.998 1 ERROR manila  CONSTRAINT si_share_server_fk FOREIGN KEY(share_server_id) REFERENCES share_servers (id)
2024-01-20 19:17:48.998 1 ERROR manila )CHARSET=utf8 ENGINE=InnoDB
2024-01-20 19:17:48.998 1 ERROR manila
2024-01-20 19:17:48.998 1 ERROR manila ]
2024-01-20 19:17:48.998 1 ERROR manila (Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-20 19:17:48.998 1 ERROR manila
(feature/mpc/Senlin&Manila)root@ctl1:~#
```

**Comment by mnaser** [comment]
I think moving forward we're going to rely on the 2023.2 images, we will remove the Zed images on GHCR as they seem to have been broken.
