### ISSUE TITLE
Bug: enabling cluster-autoscaler breaks cluster creation

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/atmosphere#912]
We've discovered an interesting bug. When creating a cluster without the cluster autoscaler label there are no problems, but if we create a cluster with that label included `auto_scaling_enabled=true` (or check the enable cluster autoscaling checkbox in Horizon) the creation process instantly fails. The stacktrace we get is:

```log
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server [None req-0698cc45-f736-402e-8733-101b6d408366 6ac1b07923ef471baffb46c78014dc57 618850dacc1242f0b0ca04b988c4add7 - - default -] Exception during message handling: FileNotFoundError: [Errno 2] No such file or directory: 'helm'
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/server.py", line 165, in _process_incoming
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/dispatcher.py", line 309, in dispatch
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/dispatcher.py", line 229, in _do_dispatch
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum/conductor/handlers/cluster_conductor.py", line 191, in cluster_delete
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     cluster_driver.delete_cluster(context, cluster)
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/driver.py", line 278, in delete_cluster
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     resources.ClusterAutoscalerHelmRelease(self.k8s_api, cluster).delete()
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/helm.py", line 99, in __call__
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     return super().__call__()
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/helm.py", line 39, in __call__
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     return super().__call__(
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/helm.py", line 26, in __call__
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     return processutils.execute("helm", *self.COMMAND, *args, **kwargs)
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_concurrency/processutils.py", line 395, in execute
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     obj = subprocess.Popen(cmd,
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/eventlet/green/subprocess.py", line 58, in __init__
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     subprocess_orig.Popen.__init__(self, args, 0, *argss, **kwds)
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     self._execute_child(args, executable, preexec_fn, close_fds,
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server     raise child_exception_type(errno_num, err_msg, err_filename)
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server FileNotFoundError: [Errno 2] No such file or directory: 'helm'
magnum-conductor-1 magnum-conductor 2024-01-22 17:31:02.922 9 ERROR oslo_messaging.rpc.server 
```

We've also found that deleting a cluster also returns the `No such file or directory: 'helm'` error regardless of if the cluster had autoscaling enabled or not.

The deletion error I think can be found at https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/driver.py#L266-L278 (where the cluster delete function is deleting the resource regardless of if it exists or not) and the creation error at https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/resources.py#L2140-L2141 where the logic only attempts to deploy it the label has been set to true.

We are using the Vexxhost-provided Ubuntu image for Kubernetes 1.27.4 (https://object-storage.public.mtl1.vexxhost.net/swift/v1/a91f106f55e64246babde7402c21b87a/magnum-capi/ubuntu-2204-kube-v1.27.4.qcow2)

**Comment by mnaser** [comment]
Hi @runlevel-six -- I think the most recent images we put out are missing Helm.

https://github.com/vexxhost/atmosphere/commit/142c13e9367042884ca11fad282f6a403f3cb16d

The commit above solves the issue, I suggest using that newer image and you should be good to go.
