### ISSUE TITLE
Designate upgrade from Zed to Bobcat failes

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#985]
When applying the latest Bobcat images from Designate the upgrade failes with the following DB error:

```
+ designate-manage database sync
An error has occurred:
Traceback (most recent call last):
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (3780, "Referencing column 'zone_id' and referenced column 'id' in foreign key constraint 'shared_zones_ibfk_1' are incompatible.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/openstack/lib/python3.10/site-packages/designate/cmd/manage.py", line 122, in main
    fn(*fn_args)
  File "/var/lib/openstack/lib/python3.10/site-packages/designate/manage/database.py", line 79, in sync
    alembic_command.upgrade(
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/lib/openstack/lib/python3.10/site-packages/designate/storage/sqlalchemy/alembic/env.py", line 83, in <module>
    run_migrations_online()
  File "/var/lib/openstack/lib/python3.10/site-packages/designate/storage/sqlalchemy/alembic/env.py", line 77, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/var/lib/openstack/lib/python3.10/site-packages/designate/storage/sqlalchemy/alembic/versions/b20189fd288e_shared_zone.py", line 36, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/operations/ops.py", line 1260, in create_table
    return operations.invoke(op)
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/operations/base.py", line 401, in invoke
    return fn(self, operation)
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/ddl/impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "/var/lib/openstack/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
    ret = self._execute_context(
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/var/lib/openstack/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/lib/openstack/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (3780, "Referencing column 'zone_id' and referenced column 'id' in foreign key constraint 'shared_zones_ibfk_1' are incompatible.")
[SQL:
CREATE TABLE shared_zones (
        id CHAR(32) NOT NULL,
        created_at DATETIME,
        updated_at DATETIME,
        zone_id CHAR(32) NOT NULL,
        project_id VARCHAR(36) NOT NULL,
        target_project_id VARCHAR(36) NOT NULL,
        PRIMARY KEY (id),
        CONSTRAINT unique_shared_zone UNIQUE (zone_id, project_id, target_project_id),
        FOREIGN KEY(zone_id) REFERENCES zones (id) ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by mpiscaer** [comment]
Thanks

**Comment by ricolin** [comment]
@mpiscaer 
I have proposed the fix here: https://review.opendev.org/c/openstack/designate/+/910322
But as it touches DB migration path, not sure if it going to be able to backport to Bobcat by designate team.
I will keep an eye on it. 
As workaround, we can adapt following steps to designate database:
* If table `shared_zones` not yet created do:
  `ALTER DATABASE DEFAULT CHARACTER SET utf8mb4;`
* If table `shared_zones` created or any other table already affected with character set to `utf8mb3`:
  `ALTER TABLE $TABLE_NAME CONVERT TO CHARACTER SET utf8mb4;`
  and make sure table `shared_zones` is converted if needed

Once above change is done, you should be able to rerun the upgrade.

**Comment by mpiscaer** [comment]
I wanted to test this out, but I came across #993

**Comment by mpiscaer** [comment]
I have tested the upgrade with the alter command.
I did twice a upgrade on different clusters. First a upgrade where I first did the alter command.
I run the following commands:
`ALTER TABLE service_statuses CONVERT TO CHARACTER SET utf8mb4;`
`ALTER DATABASE DEFAULT CHARACTER SET utf8mb4;`

This set the default character set.

The second time that I did a upgrade I run the playbook from Designate, till will make the DB sync fail with the error but does not create the shared_zone table. So I could just use the above commands to set the default CHARACTER.

**Comment by ricolin** [comment]
Thanks for the feedback,

BTW, I -1 workflow on that community patch as I was wondering if there contains default differences between different db platforms, will cycle back to that patch when I got time.

**Comment by ricolin** [comment]
> Thanks for the feedback,
> 
> BTW, I -1 workflow on that community patch as I was wondering if there contains default differences between different db platforms, will circle back to that patch when I got time.

removed that -1, I think it should works for all in general
